### ISSUE TITLE
Hey, update it to 1.10.x

### ISSUE THREAD

**Issue by Bodyash** [fromgate/Elytra#4]
Я уже отправил реквест, работает отлично!

**Comment by AndrewBastin** [comment]
Hi there,

When I tried to build from source, I encountered this issue in Util.java @ line 121 (Type mismatch between int and boolean)...

Well.. I made a fix for it and it works....
Here is the modified isPlayerGliding method:

`public static boolean isPlayerGliding(Player player){
        return ((LivingEntity) player).isGliding();
    }
`

Hope this helps :smile:

**Comment by Bodyash** [comment]
![default](https://cloud.githubusercontent.com/assets/2454569/16570136/70ef0cb2-4248-11e6-855d-8ad4d7229fc6.PNG)

No errors.

**Comment by AndrewBastin** [comment]
I am getting the error when using craftbukkit 1.10, 1.9 works fine.... And on the 1.10 error logs, in the stack trace this was shown as the source of the problem...

**Comment by AndrewBastin** [comment]
And isnt it cC() in the source ???

(Sorry, sending from a mobile)

**Comment by Leymooo** [comment]
/*Оффтоп
@Bodyash Не могли бы вы пожалуйста скинуть перевод ChangeSkin?
*/

**Comment by Bodyash** [comment]
@AndrewBastin For 1.9 server there is cC() method. For 1.10 (Using Craftbukkit core 1_10_R1) there is no cC() method, so in my fork i`m using cG() method. Doesnt know, why Spigot developers change it  in every version.

**Comment by Bodyash** [comment]
@Dimatert9 https://github.com/games647/ChangeSkin/pull/31/commits/1343f375d6f3449e6d6c0c024fcb4d41b491727a

**Comment by AndrewBastin** [comment]
@Bodyash but still, would'nt it be better to switch it to my code as we can maintain the support for 1.9 and 1.10... And Most probably that method wont be deprecated that fast...

**Comment by fromgate** [comment]
Updated: https://dev.bukkit.org/bukkit-plugins/elytra/files/7-elytra-v0-1-2/
